### ISSUE TITLE
Unwanted docker push in demo

### ISSUE THREAD

**Issue by wuleninja** [tilt-dev/tilt-avatars#17]
Hi! Very nice demo! And nice piece of technology.
I've been trying to use and understand it, by reading the code of the demo (in `/tmp/tilt-demo-1643195028/github.com/tilt-dev/tilt-avatars`).
Something that I don't quite understand: how come `tilt up` does not work, when the demo clearly does?
The cause seems to be this:

```sh
Build Failed: docker push: pushing image "docker.io/library/tilt-avatar-api": denied: requested access to the resource is denied
```

But I don't see where in the project a `push` has been required. It would be super nice to be able to track the origin of each log line. 

Anyway, this `push` does not occur when the demo runs with `tilt demo`.

**Comment by wuleninja** [comment]
Reading Tilt's code, i've figured out that my question is stupid. The push comes from Tilt. What I do not know yet, is how to replicate what the `tilt demo` does for the cluster to allow for local pushes.

**Comment by snigdha920** [comment]
I also had the same issue, resolved it by explicitly specifying the repository in the `docker_build` step in the Tiltfile: 

```Starlark
docker_build(
    'docker.io/snigdhasettlemint/tilt-avatar-api',
    context='.',
    dockerfile='./deploy/api.dockerfile',
    only=['./api/'],
    live_update=[
        sync('./api/', '/app/api/'),
        run(
            'pip install -r /app/requirements.txt',
            trigger=['./api/requirements.txt']
        )
    ]
)
```

and also changing the image in the deployment deploy/api.yaml:

```yaml
      containers:
        - name: tilt-avatar-api
          image: docker.io/snigdhasettlemint/tilt-avatar-api
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              port: 5000
              path: '/ready'
```

And the same for 'tilt-avatar-web'. The reason we get this error is we're trying to push to docker.io/library and Docker Hub expects images to be pushed to a repository path that includes our username (or an organization we have permissions to push to), rather than the default library namespace, which is reserved for official images.

-----

I'm interested in creating a PR that automates these changes, so users can pass in the repository through CLI (? or the preferred way to input variables in Starlark), like:

```bash
tilt up --imageRepository docker.io/snigdhasettlemint
```

and the prefixes `docker.io/snigdhasettlemint` in the docker_build step. Please let me know your feedback on how I can implement this!
